codecov:
  require_ci_to_pass: yes
  wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: '70...90'
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 75%
        threshold: 5%

# Flag configuration for intelligent CI with carryforward
# This enables partial test execution while maintaining coverage accuracy
flags:
  functions:
    paths:
      - src/functions/
      - test/functions/
    carryforward: true

  lib:
    paths:
      - src/lib/
      - test/lib/
    carryforward: true

  services:
    paths:
      - src/services/
      - test/services/
    carryforward: true

  scripts:
    paths:
      - src/scripts/
      - test/scripts/
    carryforward: true

  # Comprehensive integration flag for full test runs
  integration:
    paths:
      - 'src/**/*.ts'
      - 'test/**/*.ts'
    carryforward: false

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - 'dist/'
  - 'coverage/'
  - 'node_modules/'
  - 'scripts/'
  - '*.config.*'
  - '*.md'
  - 'CHANGELOG.md'
  - '*.json'
  - '*.yml'
  - '*.yaml'
  - '.github/'
