[build]
  functions = "dist/functions"
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch", "cheerio"]

# Function-specific configurations
[functions."sync-jobs"]
  schedule = "0 */6 * * *"  # Run every 6 hours

# Redirects and routing
[[redirects]]
  from = "/api/jobs"
  to = "/.netlify/functions/sync-jobs"
  status = 200

[[redirects]]
  from = "/api/jobs/manual"
  to = "/.netlify/functions/sync-jobs?manual=true"
  status = 200

# Security headers for all functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    # CORS headers
    Access-Control-Allow-Origin = "https://yourwordpresssite.com"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Max-Age = "86400"
    
    # Security headers
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https:; frame-ancestors 'none';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), sync-xhr=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Custom headers for API identification
    X-API-Version = "1.0.0"
    X-Service = "DriveHR-Sync"

# Edge function settings for better performance
[edge_functions]
  # Add any edge functions if needed

# Environment-specific settings
[context.production.environment]
  LOG_LEVEL = "info"
  ENVIRONMENT = "production"

[context.deploy-preview.environment]
  LOG_LEVEL = "debug"
  ENVIRONMENT = "staging"

[context.branch-deploy.environment]
  LOG_LEVEL = "debug"
  ENVIRONMENT = "development"

# Plugin configurations (if using Netlify plugins)
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = false